### ISSUE TITLE
DataType Stats are not updated 

### ISSUE THREAD

**Issue by russelldb** [basho/riak_kv#1017]
https://github.com/basho/riak_kv/blob/develop/src/riak_kv_stat.erl#L274 expects `{Type, actor_count, COunt}` but gets `{actor_count, Count}` https://github.com/basho/riak_kv/blob/develop/src/riak_kv_pb_crdt.erl#L136

**Comment by russelldb** [comment]
Actually, this report maybe incorrect. Will investigate UK tomorrow.

**Comment by seancribbs** [comment]
I'm currently writing a riak_test to verify.

**Comment by seancribbs** [comment]
^^ @jburwell

**Comment by seancribbs** [comment]
We discovered that the test code was not exercising the datatype API on read, instead using plain KV fetches. This meant that the actor counts would not be recorded because we were not extracting the CRDT from the value. I'm still modifying the `verify_riak_stats` test to check the datatype stats and will mention this issue when sending a PR.

^^ @matthewvon @russelldb
