### ISSUE TITLE
Riak should provide a single, fast HTTP REST API for deleting an entire bucket

### ISSUE THREAD

**Issue by roncemer** [basho/riak_kv#1033]
I realize that this issue exists because of Riak's design decision to lump all buckets together.  However, this is a huge problem for time-series data where you only want to keep the most recent history in Riak.

Riak needs to have a configuration option, much like mysql's innodb_file_per_table, which allows Riak to store each bucket under its own directory which can be easily and quickly deleted via an HTTP REST API.

Because of this issue, I've had to migrate from Riak to ElasticSearch.  Deleting 30 million keys in a 6-node Riak cluster causes the cluster to become responsive for up to 12 hours at a time.  Due to bugs in Riak's streaming list keys operation, Riak cuts off the result set before all of the keys are received, so the operation has to be repeated, from scratch, multiple times until Riak finally returns an entire result set containing all of the keys to be deleted.

These problems have resulted in Riak becoming unresponsive for production queries, for hours at a time.  Not what you want in a big-data store.

I'm sorry, but for production use, Riak just isn't there.  I've given the Riak team 1.5 years to correct the issues, but the issues persist.  Out of the box, it looks like a shiny new toy.  But bugs in listing keys and querying data under load (can't get the full result set without Riak terminating the query prematurely), combined with the inability to quickly delete a bucket, half-hearted and buggy map reduce implementation, ridiculously short five-second JavaScript timeout, and choice of non-concurrent LevelDB over concurrent RocksDB or other concurrent storage engine, relegate Riak to experimental use.  It definitely cannot handle the most common, real-world, big data tasks.  Add in Riak's general tendency toward instability, and you have a Sad Tuba scenario.

I recommend looking at ElasticSearch's design principles, and re-working Riak to be more in line with those principles.  Pretty much everything Riak got wrong, ElasticSearch got right.  I've been working full-time with Riak, running in a production environment, for the past year-and-a-half.  So I do know what I'm talking about.  After migrating to ElasticSearch, I'm able to run smaller servers, get the data out in 1/100th the time, run aggregation queries, and have the cluster do more of the work for me (less summarization done locally).

Seriously.  The Riak team should install ElasticSearch, play with it for a few weeks, and see the difference.  It's shocking.

**Comment by aphyr** [comment]
> I recommend looking at ElasticSearch's design principles, and re-working Riak to be more in line with those principles.

![selfie-1](http://i.imgur.com/ribKjoe.png)

**Comment by andrewjstone** [comment]
Basho has repeatedly stated on the mailing list and elsewhere that list-keys is not meant for production use. The problems are much more complex than you make them out to be and the tone of this issue is insulting. Riak is designed and built by hardworking engineers who study and build distributed systems for a living. Very specific tradeoffs were made in the implementation of Riak and like any large, well-tested, complex software product, it continues to be improved. Query-ability is certainly an issue with Riak, and it is certainly not optimal for time-series data at the moment. Distributed indexing and deletion in an optimistcally replicated, eventually consistent data store is a non-trivial problem. It's especially hard if you don't want to lose data. The proposed solution conflates namespacing with storage location and provides no solutions to the underlying problems of data distribution and partition tolerance as currently implemented. Closing.

**Comment by roncemer** [comment]
Interesting response.  How is it that ES is able to get this right, and Riak is not, except that the Riak team stubbornly insists on throwing all buckets into the same LevelDB files, rather than segregating them into separate LevelDB directories?  This solution is simple and elegant, and clearly gives ES the upper hand in the areas of query-ability and quick deletion of expired time-series data (or other massive amounts of data which are no longer needed, for that matter).

The tone was not intended to be insulting.  I'm an experienced, veteran Riak user offering feedback which could result in some wonderful and very useful improvements to Riak.  The work of the Riak developers is greatly appreciated.  However, the Riak designers have made a few serious design decisions which clearly have no justifiable cause.  As a result, Riak is a crippled, hamstrung product which is not capable of handling problems involving time-series data.  Unfortunately, that happens to be one of the most popular uses for a K/V store of the NoSQL persuasion.

Pardon my lack of tact.  Just trying to help you guys get back on your feet.  Unless these fixes are implemented, expect to see Riak fade into obscurity.  It has been an incredible disappointment, all because of a few silly and unnecessary design mistakes.

**Comment by aphyr** [comment]
Brief note that while your painful experience with Riak performance is legitimate and shared by others, Basho engineers may have had other considerations, like "avoiding massive data loss", that led them to make different design decisions than the Elasticsearch team.

**Comment by seancribbs** [comment]
Thank you for your feedback. 

While ES does have attractive features, we simply have different design goals. We are improving queryability (e.g. the Solr integration in 2.0), but if ES fits your needs better, you should use it and be happy. Many people are happy with the tradeoffs that Riak makes and don't need advanced query capabilities; Riak will not fade into obscurity just because your use-case doesn't fit. I regret that you had a rough time with it, but it can't be everything to everyone.

Best of luck to you.
