### ISSUE TITLE
error,mailbox_overload when 1 node left the cluster

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak_kv#1039]
I'm running a 5 node cluster, Riak 2.0.1, Ubuntu 14.04, 64GB RAM, private gigabit network between nodes.

Recently a hard drive have failed on 1 of the nodes so I had to shut it down. Just a few minutes after I did riak-admin down riak@10.0.1.3 my application started to receive "error,mailbox_overload" on all requests. This happened from all remaining 4 nodes. Restarting Riak helps for a few minutes then it goes again.
There is no high load on the server, no more than 10 requests per second. Whats causing this and how to avoid this situation? My whole application became unavailable with just 1 of 5 riak nodes down.. 

My messages to riak-users list left unanswered.

**Comment by oleksiyk** [comment]
It was the AAE that was recovering keys by thousands and it took it 5 hours before Riak started replying on requests. I tried disabling AAE (passive) and it helped with load of course but the Read Repair is not the best solution. 

Is there any way to reduce impact caused by AAE so that riak cluster will continue to answer requests?

**Comment by slfritchie** [comment]
Fixed by this PR in the 1.4 branch: https://github.com/basho/riak_kv/pull/754
Fixed by this PR in the develop branch: https://github.com/basho/riak_kv/pull/785

You said that you were using Riak 2.0.1.  Did you have the AAE throttle disabled?  That throttle is quite verbose when it activates.

**Comment by oleksiyk** [comment]
I didn't configure the AAE throttle tiers at all, so it was running with some defaults. Yes, there were many messages like this:

```
2014-11-07 07:58:58.756 [info] <0.506.0>@riak_kv_entropy_manager:perhaps_log_throttle_change:849 Changing AAE throttle from 0 -> 5000 msec/key, based on maximum vnode mailbox size 4683 from 'riak@10.0.1.5'
```

**Comment by slfritchie** [comment]
Those messages indicate that the throttle was indeed working.  (Your mailing list mention of "console.log" only had 11 mentions total, on the afternoon of 2014-11-04.)

The repairee/repair destination node doesn't have sufficient resources to absorb the repairs from AAE.  You can tune the throttle to be more aggressive with its behavior[1], and/or try to address the resource limitation (probably disk bandwidth) on the repairee node.

[1] http://docs.basho.com/riak/latest/ops/advanced/aae/#Configuring-AAE

**Comment by oleksiyk** [comment]
Yes, the problem I described in mailing list happened few days ago and it wasn't too much time before the cluster settled. 

But yesterday problem with replaced node (because of the failed disk) resulted in 5+ hours of AAE during which the cluster was unavailable to the application.

The disk system was a software RAID0 setup using four 64MB Cache SATA 6.0Gb/s disks. Do you think switching to hardware RAID can help?

**Comment by oleksiyk** [comment]
You mentioned that the problem is already fixed a year ago in develop branch, is that PR a part of 2.0.1 already?

**Comment by slfritchie** [comment]
Those PRs are for the AAE throttle feature, which were apparently active but not sufficiently tuned for your environment, sorry.

As for making improvements to your hardware, that's a tough & big subject.  Once you exhaust Basho's advice at [0], then Brandan Gregg's advice [1], [2] and his "Systems Performance" book are among the best I've encountered.  I personally don't like hardware RAID controllers because most don't keep operations statistics per disk, so it's very difficult to see if one disk is overloaded or slow/stuttering.  Also, their options for stripe sizes are far too small, IMHO: depending on the Riak workload(s) expected, I frequently recommend 4MByte or larger RAID stripe widths.  But then when you create the file system, you _must must must_ tell "mkfs" (or whatever utility) the underlying stripe size, or you'll end up with file system metadata IOPS on only one drive (worst case) or only half instead of spread across all stripe members.

[0] http://docs.basho.com/riak/latest/ops/tuning/linux/
[1] http://www.brendangregg.com/usemethod.html
[2] http://www.brendangregg.com/USEmethod/use-linux.html

**Comment by oleksiyk** [comment]
The [0] was already exhausted. Will try others, many thanks!

**Comment by slfritchie** [comment]
Thank you for reporting your experience.  It is in a report I'm writing about AAE repair and next steps for improving it.

**Comment by oleksiyk** [comment]
Thanks, I didn't expect AAE to bring my cluster and application down so when it happened under live load there was a bit of panic. At that moment I tried to setup AAE tiers but I didn't notice that the example in the documentation is wrong, so Riak even didn't start with this:

http://docs.basho.com/riak/latest/ops/advanced/aae/#Configuring-AAE

```
anti_entropy.throttle.tier1.mailbox_size = 0
anti_entropy.throttle.tier1.delay = 5ms
anti_entropy.throttle.tier1.mailbox_size = 50
anti_entropy.throttle.tier1.delay = 10ms
anti_entropy.throttle.tier1.mailbox_size = 100
anti_entropy.throttle.tier1.delay = 15ms
```

All lines have 'tier1' in them instead of tier1, tier2, tier3
