### ISSUE TITLE
Package for Ubuntu precise/riak_2.1.4-1_amd64.deb broken! [JIRA: RIAK-2499]

### ISSUE THREAD

**Issue by whyteks** [basho/riak_kv#1393]
Automatic update to riak 2.1.4 perfomed by puppet broke riak across our cluster. (ok, auto update to 'latest' not such a great idea)

This is the change in the packages postinst from 2.1.3:

x@xx:/tmp$ diff 2.1.3/postinst 2.1.4/
29,31d28
< chown -R riak:riak /usr/lib/riak
< chown -R riak:riak /etc/riak
<

The result is that the .schema files (at least) in /usr/lib/riak/lib remain as owner:root and perms:600 and therefore riak cannot read them and cannot start.

(I recognize this might not be the correct place to post this issue, I am waiting for subscription confirmation to riak-users@lists.basho, please excuse me for feeling the need to bring this to somebodies attention ASAP.)

**Comment by deejay1** [comment]
I can confirm this issue, temporary workaround is doing a

``` bash
chown -R riak:riak /usr/lib/riak/
```

**Comment by JeetKunDoug** [comment]
First, thank you for pointing out the packaging issue. We actually made the files under /usr/lib/riak root:root on purpose (see basho/node_package#196 for more information), but on our build machine the filesystem permissions were unfortunately set improperly for the Ubuntu 12 build. A better (and more secure) workaround would be to change the file mode to make sure it is readable (a+r), rather than changing the owner to riak:riak.

`chmod -R a+r /usr/lib/riak`

We will get the packages fixed soon, and again, thanks for pointing out the issue.

**Comment by JeetKunDoug** [comment]
To close the loop, riak_2.1.4-2_amd64.deb is now posted at http://docs.basho.com/riak/kv/2.1.4/downloads/

Direct link is http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.4/ubuntu/precise/riak_2.1.4-2_amd64.deb.

I'm sorry for the inconvenience this caused you, and thanks again for letting us know of this packaging issue.

I'm going to close this issue - please let us know if you have any further issues.

**Comment by Basho-JIRA** [comment]
Closed in GH so closing JIRA issue.  Updated package has been posted. 

**_[posted via JIRA by Patricia Brewer]**_

**Comment by deejay1** [comment]
It seems like the trusty package is also broken this way...
