### ISSUE TITLE
Repository has no license

### ISSUE THREAD

**Issue by sopotc** [basho/riak_kv#1856]
Having a license would bring some clarity on the feasibility of contributions and permissiveness on using the code.

**Comment by martinsumner** [comment]
Thank-you, I hadn't noticed we were missing the Apache license from riak_kv as well.  It has been raised that there is also 
a missing license from [riak_repl](https://github.com/basho/riak_repl), and it has been acknowledged that riak_repl should have an Apache license.

We're presently waiting for permission to formally resolve this, but it is expected that will be forthcoming in the next month. We're not expecting there to be an issue, the license is absent due to an oversight - but we want to have formal permission from the owners of the ex-basho assets before fixing it.
