### ISSUE TITLE
/stats crashes on Mountain Lion

### ISSUE THREAD

**Issue by roidrage** [basho/riak_kv#386]
When trying to access /stats it crashes hard on me, here's the output from the response and the error that pops up in the logs:

https://gist.github.com/3496819

`riak-admin status` succeeds, but only after a timeout. It seems to have trouble fetching the number of processors, as this line comes up in the output: `cpu_nprocs : {error,timeout}`

Using Riak 1.2.0, binary distribution, with the included Erlang. Anything I could do to provide more info or to get this working temporarily? Thanks!

**Comment by russelldb** [comment]
Is this _everytime_ you call it or is it intermittent?

Would be nice to know a bit about your machine too, please. I'm assuming 64-bit? Is ML only 64bit?

**Comment by roidrage** [comment]
It happens every time I request the /stats endpoint, yes.

ML is only 64bit I think, and so is my MacBook Air :) Anything else I could provide or try out?

**Comment by russelldb** [comment]
Thanks, man. I'm looking into it. I have to get an ML machine, 'cos all seems fine on 10.7. Sorry for the difficulty. The problem seems to be in `cpu_sup`, so to test that, maybe start an erlang shell and run 

```
cpu_sup:nprocs().
[cpu_sup:M() || M <- [avg1, avg5, avg15]].
```

And see if that crashes. Would be super cool if you could try it once in the erlang we ship with Riak and once in another (if you have some other erlang install lying around that you built yourself on the machine in question.)

**Comment by roidrage** [comment]
Just compiled R15B01 on ML, and I'm getting the same result. So I reckon that's not Riak's fault in this case.

**Comment by roidrage** [comment]
Sorry, forgot to say that it's only `cpu_sup:nprocs()` that fails. Fetching the averages works, without an error at least, here's a sample of running it: `[284,215,174]`

**Comment by russelldb** [comment]
This was fixed by https://github.com/basho/riak_kv/pull/415
