### ISSUE TITLE
AAE fold requests can be forwarded to remote nodes?

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_kv#621]
This is a placeholder, to follow up on something that popped up during a core/kv meeting.  It may be possible that an ?FOLD_REQ vnode op, initiated by AAE tree rebuilding, can be forwarded to a remote node in corner cases surrounding ownership change?

**Comment by jtuple** [comment]
We do forward vnode requests indiscriminately. The plan has always been to add a notion of local-only vnode commands that we don't forward, but alas, haven't done that yet.

During testing, the `riak_kv_vnode:get_hashtree()` query was sometimes forwarded and would break things during cluster transitions, hence this lovely addition:
https://github.com/basho/riak_kv/blob/master/src/riak_kv_vnode.erl#L480-L481

Folds were likely overlooked because forwarding them wouldn't break anything (unlike the hashtree pid stuff that would cause things to crash). The fold just ends up with some extra work if you hit a rare corner case. Nothing critical.

We probably should fix this in this release cycle, esp. if we decide to change the FOLD_REQ signature.

**Comment by jtuple** [comment]
This was fixed as part of basho/riak_kv#626 and basho/riak_core#354
