### ISSUE TITLE
riak_kv_vnode:handle_overload_command() does not handle everything

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_kv#753]
The offending clause is here: https://github.com/basho/riak_kv/blob/c00bdb4e1cccad553920c3119655f1083b4fe680/src/riak_kv_vnode.erl#L406

When we're overloaded, we can't have riak_core_vnode_proxy throwing away commands without any response at all.  For example, problems reported with KV backend status, 2I operations, bucket fold operations; all hanging or timing out in unexpected ways.

**Comment by runesl** [comment]
IMHO, the desired behaviour would be to always complete KV_VNODE_STATUS_REQ. I.e.also in overload situations. The operators need their stats to return, so they know if the node is alive and well or needs restart.

The command types serving user requests should return an overload response like is already done for PUT and GET.

**Comment by rzezeski** [comment]
+1 to this. We should be returning an error response to callers so they at least know something went wrong. I imagine the current implementation could cause process count to grow and message queues to back up as things wait for a response.

One specific thing I wonder about is AAE tree building during overload (as it requires folding over KV data). IIRC when AAE was first written it made assumptions that some operations would always make progress. I think we eventually fixed that by adding timeouts everywhere but if we didn't a bug like this could cause issues for AAE.

**Comment by evanmcc** [comment]
in: https://github.com/basho/riak_kv/blob/develop/src/riak_kv_get_fsm.erl#L107-L124
and: https://github.com/basho/riak_kv/blob/develop/src/riak_kv_put_fsm.erl#L142-L159

There is another potential overload path.  These overloads come from sidejob keeping watch on the number of get and put fsms that are live at any one time (https://github.com/basho/sidejob/blob/develop/src/sidejob_supervisor.erl#L52-L58).  It'd be nice to differentiate these, perhaps by changing the plain {error, overload} message to be specific to the kind of overload that is being encountered.

cc @angrycub @jtuple

**Comment by andrewjstone** [comment]
I propose changing the last clause [here](https://github.com/basho/riak_kv/blob/c00bdb4e1cccad553920c3119655f1083b4fe680/src/riak_kv_vnode.erl#L406) to the following

``` erlang
handle_overload_command(_, Sender, _) ->
    riak_core_vnode:reply(Sender, {error, mailbox_overload}).
```

However I've been having trouble testing it. I was trying to put the cluster into overload and run a list_keys operation after suspending all the vnodes, similar to the current overload test which suspends a vnode for a given hotkey to easily put it into overload. This resulted in tests that took forever and frequent zombie processes requiring reboots on OS X. In general it's a frustrating testing process. 

Currently our code will just hang on overload requests instead of returning an error. The change above always returns an `{error, mailbox_overload}` tuple instead. This may crash unexpecting callers of course. I think a crash is better than a hang, but would like to hear some opinions. I'm also open to testing suggestions as this is coming down to the wire here and I'm kind of at a loss.

@jtuple @evanmcc @slfritchie

**Comment by slfritchie** [comment]
Andrew, the strategy that I've used in the past is:
1. Change the overload limit from its default 10K to something like 100 or 50 or lower.
2. Use `sys:suspend()` to suspend some vnode procs
3. Apply a enough load so that the suspended vnode procs have mailboxes larger than #1's limit.

**Comment by andrewjstone** [comment]
Implemented overload handling for coverage queries. I think however that I may need to add code for `delete` before I can close this out.

**Comment by andrewjstone** [comment]
Actually, `delete` is really just a put of a tombstone. Therefore there is nothing to change for overload handling. Closing as complete.
