### ISSUE TITLE
Make AAE read repair throttle tunable

### ISSUE THREAD

**Issue by engelsanchez** [basho/riak_kv#803]
Currently, the AAE read repair throttle introduced in 1.4.7 has a kill switch, but no way to tune its innards: it uses application environment variables to control the sleep time and the aae_throttle_limits list it uses to determine sleep time between repairs based on cluster wide vnode queue lengths. But those variables are set by the entropy manager when it's initialized to hard coded values. It would be best to allow them to be tuned from the configuration in a way that will persist

**Comment by slfritchie** [comment]
IIRC, the hard-coded values are only used if there's no entry in the application environment for a non-default tuning.  The Cuttlefish schema may/may not be optimal, but last I checked it also worked (because cuttlefish creates the proper list and drop it into the app env)?

The functions at https://github.com/basho/riak_kv/blob/develop/src/riak_kv_entropy_manager.erl#L40 for examining & changing the state of the throttle's knobs are not persistent.

**Comment by engelsanchez** [comment]
Oh wait. This code has been fixed since the version we were looking at:
https://github.com/basho/riak_kv/blob/1.4/src/riak_kv_entropy_manager.erl#L207

In the 1.4 branch, the hard coded value is taken unconditionally. I suppose we can close this. If we release again in the 1.4 branch, we should consider backporting that bit. /cc @bsparrow435
