### ISSUE TITLE
application already started pattern match bug

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_kv#929]
Since we turned on EQC for the builders, Riak KV has not been passing eunit. With `make test`, we get the following error:

```
module 'riak_kv_delete'
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
  undefined
  *** context setup failed ***
**in function riak_kv_test_util:'-do_dep_apps/2-fun-0-'/2 (src/riak_kv_test_util.erl, line 264)
in call from lists:foldl/3 (lists.erl, line 1248)
in call from riak_kv_test_util:setup/2 (src/riak_kv_test_util.erl, line 165)
**error:{badmatch,
    {error,
        {bad_return,
            {{riak_kv_app,start,[normal,[]]},
             {'EXIT',
                 {{case_clause,
                      {error,
                          {{already_started,<0.6340.3>},
                           {child,undefined,...}}}},
                  [{riak_core_stats_sup,start_server,1,[{file,...},{...}]},
                   {riak_core,register_mod,3,[{...}|...]},
                   {riak_core,register,2,[...]},
                   {riak_kv_app,start,2,...},
                   {application_master,start_it_old,...}]}}}}}}
```

Sometimes it fails on other modules too, like `riak_kv_pb_object`. You can [see the full logs](http://buildbot.bos1/builders/test-riak_kv/builds/1315/steps/shell_3/logs/stdio). I've only been able to reproduce this:
1. With EQC installed
2. With a full `make test`. Running individual suites does not show the bug.

I've tried [this patch](https://gist.github.com/reiddraper/4c23d8e67a49c1b0400c), but it just [changes the error](https://gist.github.com/reiddraper/62cb67b03b1c775e9117).

I've enlisted @vinoski to help me track this down as well.

**Comment by vinoski** [comment]
Pretty sure the unexpected `{error, …}` value originates here: https://github.com/erlang/otp/blob/maint/lib/stdlib/src/supervisor.erl#L693, so your patch is definitely needed.

Just a guess, but maybe the error moves with the patch in place because previously-started children haven't quite fully shutdown and/or unregistered their names yet, and then a new test tries to start them up again in the `riak_kv_app:start/2` function. An old child shows up as `already_started` at one instant but then it shuts down or unregisters its name quickly thereafter, while the code starting it thinks it's running, tries to proceed on that basis and then fails quickly because by then the child is no longer running.

**Comment by vinoski** [comment]
Looks like the handling of `already_started` is incomplete in these `riak_core` modules:

https://github.com/basho/riak_core/blob/develop/src/riak_core_stat_calc_sup.erl#L40
https://github.com/basho/riak_core/blob/develop/src/riak_core_stats_sup.erl#L39
https://github.com/basho/riak_core/blob/develop/src/riak_core_vnode_proxy_sup.erl#L40

**Comment by vinoski** [comment]
The `{error, {{already_started, Pid},{child,…}}}` return value from `supervisor:start_child/2` occurs when an attempt is made to start a child using a childspec providing a child id that hasn't yet been started and an MFA that starts a process that tries to register itself using a name that's already been registered.

**Comment by vinoski** [comment]
Given the previous comment, @reiddraper and I agreed that the three supervisor modules listed above need not change after all, since treating that variant of `already_started` as not being an error would be incorrect.
